### ISSUE TITLE
Audit Release Coordinator for Public Access

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-api-release-coordinator#172]
We need to review the release coordinator for any security issues. Roughly speaking:

- Releases, tasks, services, and events should be read-only to the public
- Ensure that there is no data exposed that shouldn't be

### Current scope of work

- [x] #173 - Switch to Auth0
- [x] #178 - Require services to authenticate with Auth0 tokens
- [x] #177 - Require permissions for new tasks

**Comment by dankolbman** [comment]
Regarding security around task services, we are currently sending ego service tokens along with each request to a service to allow services to verify the identity of the coordinator. There are two points here that should be addressed:
1) We should update to Auth0 machine-to-machine tokens
2) We need to also validate incoming requests from task services for tokens

This means we will have to require service owners to start sending us tokens and ensure that is being done before we stop rejecting requests without them.
If we don't do this, we risk outside traffic starting/stoping tasks at will.

**Comment by dankolbman** [comment]
Coordinator is now public.
