### ISSUE TITLE
✨ GraphQL api

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-api-release-coordinator#200]
It would be helpful for front end applications to have a graphql schema to interact with as it would allow them to utilize a more consistent api and combine the coordinator into their data sources with patterns consistent with other apis.

- [x] #195 -> #194 - Task queries
- [x] #196 -> #210 - Event queries
- [x] #197 -> #206  - Task Service queries
- [x] #198 - Release Note queries
- [x] #201 -> #219 - New Release mutation
- [x] #202 -> #219 - Cancel Release mutation
- [x] #203 -> #219 - Publish Release mutation
- [x] #221 -> #223 - New Task Service mutation
- [x] #222 -> #223 - Update Task Service mutation
- [x] #225 -> #226 - Sync Studies mutation
